# Input colors
export GUM_INPUT_PROMPT_FOREGROUND="#8a857a"
export GUM_INPUT_CURSOR_FOREGROUND="#b8650a"
export GUM_INPUT_PLACEHOLDER_FOREGROUND="#d4cab2"
export GUM_INPUT_HEADER_FOREGROUND="#b8650a"

# Choose colors
export GUM_CHOOSE_CURSOR_FOREGROUND="#b8650a"
export GUM_CHOOSE_HEADER_FOREGROUND="#b8650a"
export GUM_CHOOSE_ITEM_FOREGROUND="#8a857a"
export GUM_CHOOSE_SELECTED_FOREGROUND="#1a1612"

# Confirm colors
export GUM_CONFIRM_PROMPT_FOREGROUND="#b8650a"
export GUM_CONFIRM_SELECTED_FOREGROUND="#1a1612"
export GUM_CONFIRM_SELECTED_BACKGROUND="#b8650a"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="#8a857a"
export GUM_CONFIRM_UNSELECTED_BACKGROUND="#d4cab2"

# Filter colors
export GUM_FILTER_INDICATOR_FOREGROUND="#b8650a"
export GUM_FILTER_SELECTED_PREFIX_FOREGROUND="#b8650a"
export GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND="#d4cab2"
export GUM_FILTER_HEADER_FOREGROUND="#b8650a"
export GUM_FILTER_TEXT_FOREGROUND="#8a857a"
export GUM_FILTER_CURSOR_TEXT_FOREGROUND="#1a1612"
export GUM_FILTER_MATCH_FOREGROUND="#b8650a"
export GUM_FILTER_PROMPT_FOREGROUND="#8a857a"
export GUM_FILTER_PLACEHOLDER_FOREGROUND="#d4cab2"

# Spinner colors
export GUM_SPIN_SPINNER_FOREGROUND="#b8650a"
export GUM_SPIN_TITLE_FOREGROUND="#b8650a"

# File colors
# FIXME: I don't think all variables here are set or correct
export GUM_FILE_HEADER_FOREGROUND="#b8650a"
export GUM_FILE_CURSOR_FOREGROUND="#b8650a"
export GUM_FILE_FILE_FOREGROUND="#8a857a"
export GUM_FILE_DIRECTORY_FOREGROUND="#b8650a"
export GUM_FILE_SYMLINK_FOREGROUND="#b8650a"
export GUM_FILE_FILE_SIZE_FOREGROUND="#d4cab2"
export GUM_FILE_PERMISSIONS_FOREGROUND="#d4cab2"
export GUM_FILE_SELECTED_FOREGROUND="#1a1612"

# # Style colors (general styling)
# export FOREGROUND="#8a857a"
# export BACKGROUND="#ffffff"
# export BORDER_FOREGROUND="#d4cab2"
# export BORDER_BACKGROUND="#f2ede0"
