# Input colors
export GUM_INPUT_PROMPT_FOREGROUND="#56685d"
export GUM_INPUT_CURSOR_FOREGROUND="#4a9e6f"
export GUM_INPUT_PLACEHOLDER_FOREGROUND="#1e2d24"
export GUM_INPUT_HEADER_FOREGROUND="#4a9e6f"

# Choose colors
export GUM_CHOOSE_CURSOR_FOREGROUND="#4a9e6f"
export GUM_CHOOSE_HEADER_FOREGROUND="#4a9e6f"
export GUM_CHOOSE_ITEM_FOREGROUND="#56685d"
export GUM_CHOOSE_SELECTED_FOREGROUND="#e7efe8"

# Confirm colors
export GUM_CONFIRM_PROMPT_FOREGROUND="#4a9e6f"
export GUM_CONFIRM_SELECTED_FOREGROUND="#e7efe8"
export GUM_CONFIRM_SELECTED_BACKGROUND="#4a9e6f"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="#56685d"
export GUM_CONFIRM_UNSELECTED_BACKGROUND="#1e2d24"

# Filter colors
export GUM_FILTER_INDICATOR_FOREGROUND="#4a9e6f"
export GUM_FILTER_SELECTED_PREFIX_FOREGROUND="#4a9e6f"
export GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND="#1e2d24"
export GUM_FILTER_HEADER_FOREGROUND="#4a9e6f"
export GUM_FILTER_TEXT_FOREGROUND="#56685d"
export GUM_FILTER_CURSOR_TEXT_FOREGROUND="#e7efe8"
export GUM_FILTER_MATCH_FOREGROUND="#4a9e6f"
export GUM_FILTER_PROMPT_FOREGROUND="#56685d"
export GUM_FILTER_PLACEHOLDER_FOREGROUND="#1e2d24"

# Spinner colors
export GUM_SPIN_SPINNER_FOREGROUND="#4a9e6f"
export GUM_SPIN_TITLE_FOREGROUND="#4a9e6f"

# File colors
# FIXME: I don't think all variables here are set or correct
export GUM_FILE_HEADER_FOREGROUND="#4a9e6f"
export GUM_FILE_CURSOR_FOREGROUND="#4a9e6f"
export GUM_FILE_FILE_FOREGROUND="#56685d"
export GUM_FILE_DIRECTORY_FOREGROUND="#4a9e6f"
export GUM_FILE_SYMLINK_FOREGROUND="#4a9e6f"
export GUM_FILE_FILE_SIZE_FOREGROUND="#1e2d24"
export GUM_FILE_PERMISSIONS_FOREGROUND="#1e2d24"
export GUM_FILE_SELECTED_FOREGROUND="#e7efe8"

# # Style colors (general styling)
# export FOREGROUND="#56685d"
# export BACKGROUND="#060906"
# export BORDER_FOREGROUND="#1e2d24"
# export BORDER_BACKGROUND="#111a14"
