$osaka_bg = rgba(11221Cff)
$osaka_text = rgba(f6f5ddff)
$osaka_border = rgba(53685Bff)
$osaka_field_bg = rgba(21423780)
$osaka_accent = rgba(9eebb3ff)
$osaka_error = rgba(ff5345ff)
$osaka_highlight = rgba(2DD5B7ff)

