# Input colors
export GUM_INPUT_PROMPT_FOREGROUND="#C1C497"
export GUM_INPUT_CURSOR_FOREGROUND="#2DD5B7"
export GUM_INPUT_PLACEHOLDER_FOREGROUND="#53685B"
export GUM_INPUT_HEADER_FOREGROUND="#549e6a"

# Choose colors
export GUM_CHOOSE_CURSOR_FOREGROUND="#2DD5B7"
export GUM_CHOOSE_HEADER_FOREGROUND="#549e6a"
export GUM_CHOOSE_ITEM_FOREGROUND="#C1C497"
export GUM_CHOOSE_SELECTED_FOREGROUND="#F6F5DD"

# Confirm colors
export GUM_CONFIRM_PROMPT_FOREGROUND="#549e6a"
export GUM_CONFIRM_SELECTED_FOREGROUND="#F6F5DD"
export GUM_CONFIRM_SELECTED_BACKGROUND="#2DD5B7"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="#C1C497"
export GUM_CONFIRM_UNSELECTED_BACKGROUND="#23372B"

# Filter colors
export GUM_FILTER_INDICATOR_FOREGROUND="#2DD5B7"
export GUM_FILTER_SELECTED_PREFIX_FOREGROUND="#2DD5B7"
export GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND="#53685B"
export GUM_FILTER_HEADER_FOREGROUND="#549e6a"
export GUM_FILTER_TEXT_FOREGROUND="#C1C497"
export GUM_FILTER_CURSOR_TEXT_FOREGROUND="#F6F5DD"
export GUM_FILTER_MATCH_FOREGROUND="#2DD5B7"
export GUM_FILTER_PROMPT_FOREGROUND="#C1C497"
export GUM_FILTER_PLACEHOLDER_FOREGROUND="#53685B"

# Spinner colors
export GUM_SPIN_SPINNER_FOREGROUND="#2DD5B7"
export GUM_SPIN_TITLE_FOREGROUND="#549e6a"

# File colors
# FIXME: I don't think all variables here are set or correct
export GUM_FILE_HEADER_FOREGROUND="#549e6a"
export GUM_FILE_CURSOR_FOREGROUND="#2DD5B7"
export GUM_FILE_FILE_FOREGROUND="#C1C497"
export GUM_FILE_DIRECTORY_FOREGROUND="#2DD5B7"
export GUM_FILE_SYMLINK_FOREGROUND="#2DD5B7"
export GUM_FILE_FILE_SIZE_FOREGROUND="#53685B"
export GUM_FILE_PERMISSIONS_FOREGROUND="#53685B"
export GUM_FILE_SELECTED_FOREGROUND="#F6F5DD"

# # Style colors (general styling)
# export FOREGROUND="#C1C497"
# export BACKGROUND="#111c18"
# export BORDER_FOREGROUND="#53685B"
# export BORDER_BACKGROUND="#23372B"
