# Common
windowrule = suppressevent maximize, class:.* # Ignore maximize requests from apps. You'll probably like this.

# Browser
windowrulev2 = opacity 1.0 override, class:(firefox|Chromium|chrome)

windowrulev2 = float, title:^(Picture-in-Picture)(.*)$
windowrulev2 = pin, title:^(Picture-in-Picture)(.*)$
windowrulev2 = keepaspectratio, title:^(Picture-in-Picture)(.*)$
windowrulev2 = persistentsize, title:^(Picture-in-Picture)(.*)$

# IDEs
windowrulev2 = opacity 1.0 override, class:(Code|Emulator|jetbrains-studio|jetbrains-idea)

windowrulev2 = noborder, class:(Emulator)
windowrulev2 = noshadow, class:(Emulator)
windowrulev2 = decorate off, class:(Emulator)
windowrulev2 = immediate off, class:(Emulator)

# Video players
windowrulev2 = opacity 1.0 override, class:(mpv|vlc)

# Dialogs
windowrulev2 = float, title:^(Open File)|(Select a File)|(Choose wallpaper)|(Open Folder)|(Save As)|(Library)|(File Upload)(.*)$
windowrulev2 = center, title:^(Open File)|(Select a File)|(Choose wallpaper)|(Open Folder)|(Save As)|(Library)|(File Upload)(.*)$

# KeePassXC
windowrulev2 = workspace special:scratchpad, class:^(KeePassXC)$

# Myarchy
windowrule = float, class:^(Myarchy.)(Menu|App|BigApp)$
windowrule = center, class:^(Myarchy.)(Menu|App|BigApp)$
windowrule = size 1000 700, class:^(Myarchy.)(Menu|App)$
windowrule = size 1400 900, class:^(Myarchy.BigApp)$
