general {
    col.active_border = rgba(d4cab2ff)
    col.inactive_border = rgba(8a857a00)
}

group {
    col.border_active = rgba(d4cab2ff)
    col.border_inactive = rgb(8a857a)

    groupbar {
        col.active = rgba(f2ede0cc)
        col.inactive = rgba(ffffffaa)
        text_color = rgba(3a3530ff)
        text_color_inactive = rgba(8a857aff)
    }
}

windowrule {
    name = "Single tiled window border"
    match:float = false
    match:workspace = w[tv1]
    border_color = rgb(8a857a)
}

windowrule {
    name = "Single fullscreen window border"
    match:float = false
    match:workspace = f[1]
    border_color = rgb(8a857a)
}

