$theme_foreground = rgba(f3f3f5ff)
$theme_outline = rgba(26282dff)
$theme_input_bg = rgba(12121480)
$theme_shadow = rgba(050506ff)
$theme_accent = rgba(d97b00ff)
$theme_alert = rgba(c0392bff)
$theme_capslock = rgba(f3f3f5ff)
