#!/usr/bin/env bash

source $MYARCHY_DIR/install/lib.sh

export MYARCHY_CONFIG_DIR=$XDG_CONFIG_HOME/myarchy
mkdir -p $MYARCHY_CONFIG_DIR

export MYARCHY_SETTINGS_FILE=$MYARCHY_CONFIG_DIR/settings.env

if [[ -f $MYARCHY_SETTINGS_FILE ]]; then
	set -a && source $MYARCHY_SETTINGS_FILE && set +a
else
	touch $MYARCHY_SETTINGS_FILE
	chmod +x $MYARCHY_SETTINGS_FILE
fi

write_env_var "MYARCHY_DIR" "$MYARCHY_DIR" $MYARCHY_SETTINGS_FILE

MYARCHY_INSTANCE_ID=${MYARCHY_INSTANCE_ID:-$(gum input --header "Enter your myarchy instance ID used to identify specific local configurations (e.g. 'desktop', 'laptop')")}
write_env_var "MYARCHY_INSTANCE_ID" "$MYARCHY_INSTANCE_ID" $MYARCHY_SETTINGS_FILE

set -a && source $MYARCHY_SETTINGS_FILE && set +a
