general {
    col.active_border = rgb(56685d)
    col.inactive_border = rgba(1e2d24ff)
}

group {
    col.border_active = rgb(56685d)
    col.border_inactive = rgba(1e2d24ff)

    groupbar {
        col.active = rgba(111a14ff)
        col.inactive = rgba(060906ff)
    }
}

plugin {
    hyprexpo {
        bg_col = rgba(1e2d24ff)
    }
}

windowrulev2 = bordercolor rgba(1e2d24ff), floating:0, onworkspace:w[tv1]
windowrulev2 = bordercolor rgba(1e2d24ff), floating:0, onworkspace:f[1]

