# Input colors
export GUM_INPUT_PROMPT_FOREGROUND="#8a8a8d"
export GUM_INPUT_CURSOR_FOREGROUND="#f59e0b"
export GUM_INPUT_PLACEHOLDER_FOREGROUND="#333333"
export GUM_INPUT_HEADER_FOREGROUND="#f59e0b"

# Choose colors
export GUM_CHOOSE_CURSOR_FOREGROUND="#f59e0b"
export GUM_CHOOSE_HEADER_FOREGROUND="#f59e0b"
export GUM_CHOOSE_ITEM_FOREGROUND="#8a8a8d"
export GUM_CHOOSE_SELECTED_FOREGROUND="#eaeaea"

# Confirm colors
export GUM_CONFIRM_PROMPT_FOREGROUND="#f59e0b"
export GUM_CONFIRM_SELECTED_FOREGROUND="#eaeaea"
export GUM_CONFIRM_SELECTED_BACKGROUND="#f59e0b"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="#8a8a8d"
export GUM_CONFIRM_UNSELECTED_BACKGROUND="#333333"

# Filter colors
export GUM_FILTER_INDICATOR_FOREGROUND="#f59e0b"
export GUM_FILTER_SELECTED_PREFIX_FOREGROUND="#f59e0b"
export GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND="#333333"
export GUM_FILTER_HEADER_FOREGROUND="#f59e0b"
export GUM_FILTER_TEXT_FOREGROUND="#8a8a8d"
export GUM_FILTER_CURSOR_TEXT_FOREGROUND="#eaeaea"
export GUM_FILTER_MATCH_FOREGROUND="#f59e0b"
export GUM_FILTER_PROMPT_FOREGROUND="#8a8a8d"
export GUM_FILTER_PLACEHOLDER_FOREGROUND="#333333"

# Spinner colors
export GUM_SPIN_SPINNER_FOREGROUND="#f59e0b"
export GUM_SPIN_TITLE_FOREGROUND="#f59e0b"

# File colors
# FIXME: I don't think all variables here are set or correct
export GUM_FILE_HEADER_FOREGROUND="#f59e0b"
export GUM_FILE_CURSOR_FOREGROUND="#f59e0b"
export GUM_FILE_FILE_FOREGROUND="#8a8a8d"
export GUM_FILE_DIRECTORY_FOREGROUND="#f59e0b"
export GUM_FILE_SYMLINK_FOREGROUND="#f59e0b"
export GUM_FILE_FILE_SIZE_FOREGROUND="#333333"
export GUM_FILE_PERMISSIONS_FOREGROUND="#333333"
export GUM_FILE_SELECTED_FOREGROUND="#eaeaea"

# # Style colors (general styling)
# export FOREGROUND="#8a8a8d"
# export BACKGROUND="#121212"
# export BORDER_FOREGROUND="#333333"
# export BORDER_BACKGROUND="#1e1e1e"
