[package]
name = "myarchyctl"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "myarchyctl"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
clap_complete = { version = "4", features = ["unstable-dynamic"] }
myarchy-core = { path = "../myarchy-core", features = ["clap"] }
myarchy-host = { path = "../myarchy-host" }

[dev-dependencies]
myarchy-core = { path = "../myarchy-core", features = ["clap", "fixtures"] }
