[package]
name = "myarchyctl"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "myarchyctl"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
clap_complete = { version = "4", features = ["unstable-dynamic"] }
idle-inhibitor = { path = "../idle-inhibitor", default-features = false }
myarchy-core = { path = "../myarchy-core", features = ["clap"] }
myarchy-sys = { path = "../myarchy-sys" }
serde_json = "1"

[dev-dependencies]
myarchy-core = { path = "../myarchy-core", features = ["clap", "fixtures"] }
