[package]
name = "myarchy-core"
version.workspace = true
edition.workspace = true

[features]
clap = ["dep:clap"]

[dependencies]
anyhow.workspace = true
clap = { workspace = true, optional = true }
fd-lock.workspace = true
myarchy-idle-inhibitor.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
