<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>{{theme-name}}</string>
  <key>settings</key>
  <array>
    <dict>
      <key>settings</key>
      <dict>
        <key>background</key>
        <string>{{surface|hex}}</string>
        <key>caret</key>
        <string>{{foreground-strong|hex}}</string>
        <key>foreground</key>
        <string>{{foreground-muted|hex}}</string>
        <key>invisibles</key>
        <string>{{foreground-subtle|hex}}</string>
        <key>lineHighlight</key>
        <string>{{surface-2|hex}}</string>
        <key>selection</key>
        <string>{{surface-4|hex}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Comment</string>
      <key>scope</key>
      <string>comment</string>
      <key>settings</key>
      <dict>
        <key>fontStyle</key>
        <string>italic</string>
        <key>foreground</key>
        <string>{{foreground-subtle|hex}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>String</string>
      <key>scope</key>
      <string>string, punctuation.definition.string</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{ansi-yellow|hex}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Number</string>
      <key>scope</key>
      <string>constant.numeric</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{accent|hex}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Keyword</string>
      <key>scope</key>
      <string>keyword, storage</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{ansi-magenta|hex}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Function</string>
      <key>scope</key>
      <string>entity.name.function, support.function</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{accent|hex}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Variable</string>
      <key>scope</key>
      <string>variable</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{foreground|hex}}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Type</string>
      <key>scope</key>
      <string>entity.name.type, support.type</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{{foreground-muted|hex}}</string>
      </dict>
    </dict>
  </array>
</dict>
</plist>
