#!/usr/bin/env bash

SHOULD_BUILD_GRUB=false

sudo myarchy-lib backup-file /etc/default/grub

if grep -q '^GRUB_TIMEOUT=1' /etc/default/grub; then
	echo "GRUB timeout is already set to 1 seconds."
else
	sudo sed -i 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=1/' /etc/default/grub
	SHOULD_BUILD_GRUB=true
fi

if grep -q '^GRUB_TIMEOUT_STYLE=hidden' /etc/default/grub; then
	echo "GRUB timeout style is already set to hidden."
else
	sudo sed -i 's/GRUB_TIMEOUT_STYLE=.*/GRUB_TIMEOUT_STYLE=hidden/' /etc/default/grub
	SHOULD_BUILD_GRUB=true
fi

if grep -q '^GRUB_BACKGROUND=' /etc/default/grub; then
	sudo sed -i 's/^GRUB_BACKGROUND=/#GRUB_BACKGROUND=/' /etc/default/grub
	SHOULD_BUILD_GRUB=true
fi

if [ $SHOULD_BUILD_GRUB = true ]; then
	echo "Updating GRUB configuration..."
	sudo grub-mkconfig -o /boot/grub/grub.cfg
else
	echo "No changes made to GRUB configuration."
fi
