#!/usr/bin/env bash

SHOULD_REBUILD_DRACUT=false
SHOULD_REBUILD_GRUB=false

CONFIG_FILE="/etc/default/grub"
PARAMETER="quiet splash"

PLYMOUTH_THEME="$1"

sudo myarchy-lib backup-file "$CONFIG_FILE"

if grep -q "GRUB_CMDLINE_LINUX_DEFAULT" "$CONFIG_FILE"; then
	# Check if the parameters already exist
	if ! grep -q "GRUB_CMDLINE_LINUX_DEFAULT=.*$PARAMETER" "$CONFIG_FILE"; then
		# Append the parameters to the existing line
		sudo sed -i "s/^\(GRUB_CMDLINE_LINUX_DEFAULT='[^\']*\)/\1 $PARAMETER/" "$CONFIG_FILE"
		SHOULD_REBUILD_DRACUT=true
		SHOULD_REBUILD_GRUB=true
	fi
else
	# If the line does not exist, add it
	echo "GRUB_CMDLINE_LINUX_DEFAULT=\"$PARAMETER\"" | sudo tee -a "$CONFIG_FILE"
	SHOULD_REBUILD_DRACUT=true
	SHOULD_REBUILD_GRUB=true
fi

DRACUT_CONFIG_FILE="/etc/dracut.conf.d/plymouth.conf"

sudo myarchy-lib backup-file "$DRACUT_CONFIG_FILE"

if [ ! -f "$DRACUT_CONFIG_FILE" ]; then
	sudo touch "$DRACUT_CONFIG_FILE"
fi

if ! grep -q 'add_dracutmodules+=" plymouth "' "$DRACUT_CONFIG_FILE"; then
	echo 'add_dracutmodules+=" plymouth "' | sudo tee -a "$DRACUT_CONFIG_FILE"
	SHOULD_REBUILD_DRACUT=true
fi

current_plymouth_theme=$(plymouth-set-default-theme)
if [ "$current_plymouth_theme" != "$PLYMOUTH_THEME" ]; then
	SHOULD_REBUILD_DRACUT=true
	sudo plymouth-set-default-theme $PLYMOUTH_THEME
fi

if [ $SHOULD_REBUILD_DRACUT = true ]; then
	sudo dracut-rebuild
fi

if [ $SHOULD_REBUILD_GRUB = true ]; then
	sudo grub-mkconfig -o /boot/grub/grub.cfg
fi

# TODO: perhaps add early KMS loading
