[colors.primary]
foreground = "#C1C497"
background = "#111c18"
dim_foreground = "#9eebb3"
bright_foreground = "#F6F5DD"

[colors.cursor]
text = "#0a0f0c"
cursor = "#c1c497"

[colors.vi_mode_cursor]
text = "#0a0f0c"
cursor = "#c1c497"

[colors.search.matches]
foreground = "#C1C497"
background = "#23372B"

[colors.search.focused_match]
foreground = "#111c18"
background = "#2DD5B7"

[colors.hints.start]
foreground = "#C1C497"
background = "#23372B"

[colors.hints.end]
foreground = "#9eebb3"
background = "#23372B"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#C1C497"
background = "#23372B"

[colors.selection]
text = "#C1C497"
background = "#53685B"

[colors.normal]
black = "#23372B"
red = "#ff5345"
green = "#2dd5b7"
yellow = "#e5c736"
blue = "#549e6a"
magenta = "#9eebb3"
cyan = "#c1c497"
white = "#f6f5dd"

[colors.bright]
black = "#53685B"
red = "#ff5345"
green = "#9eebb3"
yellow = "#e5c736"
blue = "#2dd5b7"
magenta = "#9eebb3"
cyan = "#f6f5dd"
white = "#f6f5dd"

[colors.dim]
black = "#53685B"
red = "#ff5345"
green = "#2dd5b7"
yellow = "#e5c736"
blue = "#549e6a"
magenta = "#9eebb3"
cyan = "#c1c497"
white = "#f6f5dd"
