# Input colors
export GUM_INPUT_PROMPT_FOREGROUND="#7a7c80"
export GUM_INPUT_CURSOR_FOREGROUND="#d97b00"
export GUM_INPUT_PLACEHOLDER_FOREGROUND="#26282d"
export GUM_INPUT_HEADER_FOREGROUND="#d97b00"

# Choose colors
export GUM_CHOOSE_CURSOR_FOREGROUND="#d97b00"
export GUM_CHOOSE_HEADER_FOREGROUND="#d97b00"
export GUM_CHOOSE_ITEM_FOREGROUND="#7a7c80"
export GUM_CHOOSE_SELECTED_FOREGROUND="#f3f3f5"

# Confirm colors
export GUM_CONFIRM_PROMPT_FOREGROUND="#d97b00"
export GUM_CONFIRM_SELECTED_FOREGROUND="#f3f3f5"
export GUM_CONFIRM_SELECTED_BACKGROUND="#d97b00"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="#7a7c80"
export GUM_CONFIRM_UNSELECTED_BACKGROUND="#26282d"

# Filter colors
export GUM_FILTER_INDICATOR_FOREGROUND="#d97b00"
export GUM_FILTER_SELECTED_PREFIX_FOREGROUND="#d97b00"
export GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND="#26282d"
export GUM_FILTER_HEADER_FOREGROUND="#d97b00"
export GUM_FILTER_TEXT_FOREGROUND="#7a7c80"
export GUM_FILTER_CURSOR_TEXT_FOREGROUND="#f3f3f5"
export GUM_FILTER_MATCH_FOREGROUND="#d97b00"
export GUM_FILTER_PROMPT_FOREGROUND="#7a7c80"
export GUM_FILTER_PLACEHOLDER_FOREGROUND="#26282d"

# Spinner colors
export GUM_SPIN_SPINNER_FOREGROUND="#d97b00"
export GUM_SPIN_TITLE_FOREGROUND="#d97b00"

# File colors
# FIXME: I don't think all variables here are set or correct
export GUM_FILE_HEADER_FOREGROUND="#d97b00"
export GUM_FILE_CURSOR_FOREGROUND="#d97b00"
export GUM_FILE_FILE_FOREGROUND="#7a7c80"
export GUM_FILE_DIRECTORY_FOREGROUND="#d97b00"
export GUM_FILE_SYMLINK_FOREGROUND="#d97b00"
export GUM_FILE_FILE_SIZE_FOREGROUND="#26282d"
export GUM_FILE_PERMISSIONS_FOREGROUND="#26282d"
export GUM_FILE_SELECTED_FOREGROUND="#f3f3f5"

# # Style colors (general styling)
# export FOREGROUND="#7a7c80"
# export BACKGROUND="#050506"
# export BORDER_FOREGROUND="#26282d"
# export BORDER_BACKGROUND="#121214"
