[workspace]
resolver = "3"
members = ["myarchy-core", "myarchy-ctl", "myarchy-idle-inhibitor"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
clap_complete = { version = "4", features = ["unstable-dynamic"] }
fd-lock = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.11"
zbus = "5"

myarchy-core = { path = "myarchy-core" }
myarchy-idle-inhibitor = { path = "myarchy-idle-inhibitor", default-features = false }

[profile.release]
opt-level = "s"
strip = true
