general {
    col.active_border = rgb(7a7c80)
    col.inactive_border = rgba(26282dff)
}

group {
    col.border_active = rgb(7a7c80)
    col.border_inactive = rgba(26282dff)

    groupbar {
        col.active = rgba(121214ff)
        col.inactive = rgba(050506ff)
    }
}

plugin {
    hyprexpo {
        bg_col = rgba(26282dff)
    }
}

windowrulev2 = bordercolor rgba(26282dff), floating:0, onworkspace:w[tv1]
windowrulev2 = bordercolor rgba(26282dff), floating:0, onworkspace:f[1]

