#!/usr/bin/env bash

set -eEo pipefail

# VARS
export MYARCHY_DIR=${MYARCHY_DIR:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)}
export MYARCHY_INSTANCE_ID=${MYARCHY_INSTANCE_ID:-$(gum input --header "Enter your myarchy instance ID used to identify specific local configurations (e.g. 'desktop', 'laptop')")}
export DEV_TOOLS_PATH=~/dev/tools # TODO: move this

# GLOBAL SYSTEM INSTALLATION WITH PACKAGES & CONFIG
sudo cp $MYARCHY_DIR/bin/myarchy-lib /usr/local/bin/myarchy-lib
sudo pacman -Syu --noconfirm
source $MYARCHY_DIR/install/packages/all
source $MYARCHY_DIR/install/sysconfig/all

# USER CONFIGURATION
export PATH=$MYARCHY_DIR/bin:$PATH
myarchy-hyprland-plugins install hyprexpo
# myarchy-theme init
# myarchy-wallpaper init
# myarchy-deploy all
