#!/usr/bin/env bash

set -eEo pipefail

# TODO: move this, do this better
sudo chmod g+rwx /var/backups/

# VARS

export MYARCHY_DIR="$HOME/.local/share/myarchy"
export MYARCHY_INSTANCE_ID=${MYARCHY_INSTANCE_ID:-$(gum input --header "Enter your myarchy instance ID used to identify specific local configurations (e.g. 'desktop', 'laptop')")}

export DEV_TOOLS_PATH="$HOME/dev/tools"
mkdir -p $DEV_TOOLS_PATH

# DEPLOY BINARIES

source $MYARCHY_DIR/install/deploy/deploy-bin

# SYSTEM CONFIGURATION

sudo pacman -Syu --noconfirm

source $MYARCHY_DIR/install/packages/all
source $MYARCHY_DIR/install/sysconfig/all

# USER CONFIGURATION

source $MYARCHY_DIR/install/deploy/deploy-config
source $MYARCHY_DIR/install/deploy/deploy-applications

source $MYARCHY_DIR/install/usrconfig/all

myarchy-theme init
myarchy-wallpaper init
