#!/usr/bin/env bash

source $MYARCHY_DIR/install/lib.sh

install_gum() {
    install_packages gum
}

install_flatpak() {
    install_packages flatpak
    flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
}

install_git() {
    install_packages git git-delta
    install_yay_packages git-credential-oauth
}

install_net_tools() {
    install_packages curl
}

install_files_compression() {
    install_packages unzip xz zip
}

install_files_presentation() {
    install_packages bat
}

install_files_searching() {
    install_packages fd ripgrep fzf
}

install_files_manipulation() {
    install_packages jq go-yq
    install_packages python-j2cli
}

install_nvm() {
    install_packages nvm
    source /usr/share/nvm/init-nvm.sh
    nvm install --lts || echo "nvm install failed, maybe nvm is not properly configured" >&2
}

install_hyprland_plugins() {
    declare -A REPOS=(
        ["hyprland-plugins"]="https://github.com/hyprwm/hyprland-plugins"
    )

    REQUIRED_PLUGINS=$(echo 'hyprexpo' | sort -u)
    REQUIRED_REPOS=$(echo "${!REPOS[@]}" | tr ' ' '\n' | sort -u)

    hyprpm reload || echo "failed to reload hyprpm"

    enabled_plugins=$(myarchy-hyprpm-list | jq '[.[] | select(.enabled == true)]' | jq -r '.[] | "\(.plugin)"' | sort -u)
    installed_repos=$(myarchy-hyprpm-list | jq -r '.[] | "\(.repo)"' | sort -u)

    plugins_to_enable=$(comm -13 <(echo "$enabled_plugins") <(echo "$REQUIRED_PLUGINS"))
    repos_to_install=$(comm -13 <(echo "$installed_repos") <(echo "$REQUIRED_REPOS"))

    for repo in $repos_to_install; do
        local url="${REPOS[$repo]}"
        hyprpm add "$url" || echo "failed to add repo $repo with $url"
    done

    if [[ -n "$repos_to_install" ]] || [[ -n "$plugins_to_enable" ]]; then
        hyprpm update || echo "failed to update hyprpm"
    fi

    for plugin in $plugins_to_enable; do
        hyprpm enable "$plugin" || echo "failed to enable plugin $plugin"
    done
}

install_hyprlandia() {
    install_packages hyprland hyprpaper hyprcursor hyprlock hypridle hyprland-qtutils hyprland-qt-support hyprpolkitagent
    install_packages xdg-desktop-portal-hyprland xdg-desktop-portal-gtk
    install_packages qt6-wayland qt5-wayland

    install_packages uwsm libnewt

    install_packages cmake meson cpio gcc
    install_hyprland_plugins

    install_packages python-pywayland
}

install_osd() {
    install_packages swayosd
}

install_terminal() {
    install_packages alacritty
    remove_packages xterm || echo "xterm is already uninstalled, skipping"
    sudo ln -sf /usr/bin/alacritty /usr/bin/xterm # Stupid workaround to allow to run .desktop files that require by default xterm (i don't know how to change it)

    install_packages starship

    install_packages neovim
}

install_waybar() {
    install_packages waybar
}

install_wofi() {
    install_packages wofi
}

install_screenshot() {
    install_packages hyprshot satty
}

install_mako() {
    install_packages mako
}

install_screen() {
    install_packages brightnessctl
}

install_monitoring() {
    install_packages fastfetch btop
}

install_power() {
    install_packages upower power-profiles-daemon
}

install_fonts() {
    install_packages ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols

    # FIXME:
    # cargo install --git https://github.com/loichyan/nerdfix.git
}

install_audio() {
    install_packages sof-firmware
    install_packages pipewire wireplumber pipewire-audio pipewire-pulse pipewire-jack
    install_packages wiremix
}

install_bluetooth() {
    sudo systemctl enable --now bluetooth.service
    install_yay_packages bluetuith
}

install_clipboard() {
    install_packages wl-clipboard
}

install_disks() {
    install_packages gvfs udisks2
    # Automounting of usb devices
    install_packages udiskie
}

install_multimedia() {
    install_packages playerctl
}

install_backup_tools() {
    install_packages snapper snap-pac inotify-tools grub-btrfs
}

install_eza {
    install_packages eza
}

install_gum
install_flatpak
install_git
install_net_tools
install_files_compression
install_files_presentation
install_files_searching
install_files_manipulation
install_nvm
install_hyprlandia
install_osd
install_terminal
install_waybar
install_wofi
install_screenshot
install_mako
install_screen
install_monitoring
install_power
install_fonts
install_audio
install_bluetooth
install_clipboard
install_disks
install_multimedia
install_backup_tools
install_eza
