#!/usr/bin/env bash

build_dir=$(mktemp -d)

if git clone --depth 1 https://github.com/Flo-CS/idle-inhibitor "$build_dir/idle-inhibitor" &&
	(cd "$build_dir/idle-inhibitor" && makepkg -si --noconfirm); then
	echo "installed idle-inhibitor"
else
	echo "WARNING: could not install idle-inhibitor, rerun myarchy-update all once git credentials are set up" >&2
fi

rm -rf "$build_dir"
