#!/usr/bin/env bash

set -eEo pipefail

sudo cp -f --remove-destination "$MYARCHY_DIR/bin/myarchy-lib" "/usr/local/bin/myarchy-lib"

find "$MYARCHY_DIR/bin" -type f -exec cp -f --remove-destination -t $HOME/.local/bin {} +

export PATH="$HOME/.local/bin:$PATH"
