[colors.primary]
foreground = "#bebebe"
background = "#121212"
dim_foreground = "#8a8a8d"
bright_foreground = "#eaeaea"

[colors.cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.vi_mode_cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.search.matches]
foreground = "#bebebe"
background = "#333333"

[colors.search.focused_match]
foreground = "#121212"
background = "#f59e0b"

[colors.hints.start]
foreground = "#bebebe"
background = "#333333"

[colors.hints.end]
foreground = "#8a8a8d"
background = "#333333"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#bebebe"
background = "#333333"

[colors.selection]
text = "#bebebe"
background = "#333333"

[colors.normal]
black = "#333333"
red = "#b91c1c"
green = "#f59e0b"
yellow = "#ffc107"
blue = "#d35f5f"
magenta = "#eaeaea"
cyan = "#bebebe"
white = "#eaeaea"

[colors.bright]
black = "#8a8a8d"
red = "#d35f5f"
green = "#ffc107"
yellow = "#ffc107"
blue = "#f59e0b"
magenta = "#eaeaea"
cyan = "#eaeaea"
white = "#eaeaea"

[colors.dim]
black = "#8a8a8d"
red = "#b91c1c"
green = "#f59e0b"
yellow = "#ffc107"
blue = "#d35f5f"
magenta = "#eaeaea"
cyan = "#bebebe"
white = "#eaeaea"
